# Generated by Django 5.0.2 on 2024-06-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=254)),
                ('deskripsi', models.CharField(max_length=254)),
                ('author', models.CharField(max_length=254)),
                ('tahun', models.CharField(max_length=50)),
            ],
        ),
    ]
