# Generated by Django 5.0.2 on 2024-06-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('full_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='deskripsi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='buku',
            name='judul',
            field=models.CharField(max_length=245),
        ),
    ]
